# --- Colorscheme ---
include themes/noctalia.conf

# --- Options ---
cursor_trail 1
enable_audio_bell no
window_padding_width 10
strip_trailing_spaces smart
background_opacity 0.75

# --- Font ---
font_size 12.0
font_family CaskaydiaCove Nerd Font Mono

# --- Tab-Bar ---
tab_bar_edge  bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# --- Keybindings ---
map ctrl+shift+space next_layout
map ctrl+shift+z toggle_layout stack
map ctrl+shift+enter new_window_with_cwd

# Window Navigation
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# Window Resizing
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter
map ctrl+shift+backspace resize_window reset
